// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuYd2DYUTOmbP96no9oNimnHP78YbwjDE',
    appId: '1:663262636424:web:2165296dc19df0ff04f23d',
    messagingSenderId: '663262636424',
    projectId: 'lushh-da2df',
    authDomain: 'lushh-da2df.firebaseapp.com',
    storageBucket: 'lushh-da2df.firebasestorage.app',
    measurementId: 'G-8MYSQN9E07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2EDyULgHPK1h1VJ44cEilC9jLmIsN1qc',
    appId: '1:663262636424:android:7e13d81d9d27298604f23d',
    messagingSenderId: '663262636424',
    projectId: 'lushh-da2df',
    storageBucket: 'lushh-da2df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyTbdyhUh3ITjFXJRY_35jcYKzxXw3wPg',
    appId: '1:663262636424:ios:8d67711a9f91a42a04f23d',
    messagingSenderId: '663262636424',
    projectId: 'lushh-da2df',
    storageBucket: 'lushh-da2df.firebasestorage.app',
    iosBundleId: 'com.example.lushh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyTbdyhUh3ITjFXJRY_35jcYKzxXw3wPg',
    appId: '1:663262636424:ios:8d67711a9f91a42a04f23d',
    messagingSenderId: '663262636424',
    projectId: 'lushh-da2df',
    storageBucket: 'lushh-da2df.firebasestorage.app',
    iosBundleId: 'com.example.lushh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuYd2DYUTOmbP96no9oNimnHP78YbwjDE',
    appId: '1:663262636424:web:a4389b8a1177edb504f23d',
    messagingSenderId: '663262636424',
    projectId: 'lushh-da2df',
    authDomain: 'lushh-da2df.firebaseapp.com',
    storageBucket: 'lushh-da2df.firebasestorage.app',
    measurementId: 'G-X1E3CSXE97',
  );
}
